### model
model_name_or_path: /scratch/daweili5/preference_leakage/saves/Mistral-7B-v0.1/moss_oasst_lima_sft_30000
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: full
# lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
deepspeed: config/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: UltraFeedback_mistra_gemini_dpo_moss_oasst_lima
template: mistral
cutoff_len: 1024
max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Mistral-7B-v0.1/gemini_dpo_30000_moss_oasst_lima
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500